// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMw3K4inlc3vczOWoul_YxJ91dAFjXfas',
    appId: '1:137927149484:web:fe166b5463460455df1c09',
    messagingSenderId: '137927149484',
    projectId: 'pharma-homeo',
    authDomain: 'pharma-homeo.firebaseapp.com',
    storageBucket: 'pharma-homeo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8p0aqux62qNwyEHLtypC-61ERyjixTq8',
    appId: '1:137927149484:android:d7499682e2e4b94fdf1c09',
    messagingSenderId: '137927149484',
    projectId: 'pharma-homeo',
    storageBucket: 'pharma-homeo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIPLGjbBkSa_sJEdbLcJezsWIGlEMZbws',
    appId: '1:137927149484:ios:9db8b2661853369bdf1c09',
    messagingSenderId: '137927149484',
    projectId: 'pharma-homeo',
    storageBucket: 'pharma-homeo.appspot.com',
    iosBundleId: 'com.example.pharmaHomeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIPLGjbBkSa_sJEdbLcJezsWIGlEMZbws',
    appId: '1:137927149484:ios:bf762ba8645cfed2df1c09',
    messagingSenderId: '137927149484',
    projectId: 'pharma-homeo',
    storageBucket: 'pharma-homeo.appspot.com',
    iosBundleId: 'com.example.pharmaHomeo.RunnerTests',
  );
}
